### ISSUE TITLE
404 on google drive

### ISSUE THREAD

**Issue by afif-malghani** [prclaunchky/Windows-10-Super-Minimal#3]
The link results in 404 not found error on google drive.

**Comment by jkalter66** [comment]
Still 404 Not found

**Comment by joaopedromattos** [comment]
Does anybody has uploaded the iso somewhere before 404?

**Comment by ppdmartell** [comment]
Having the same 404, looks like the author is not following the repository.

**Comment by afif-malghani** [comment]
Here's a link of compiled ISO. Hope it helps. 
https://ameliorated.info/
